### ISSUE TITLE
Can't get onto the downloads site to download hobbyist bundle pre-built image

### ISSUE THREAD

**Issue by johncblacker** [PyImageSearch/Raspberry-Pi-for-Computer-Vision-RPi4CV#6]
As indicated in the e-book and on the supplemental material website page I should be able to follow the link
on the page to go to the "download" site and re-download the raspbian.img zip; however, the site wants to
send me an "activation code" to the email used when I purchased the bundle and when I put in that email address 
(blacker64@gmail.com) it reports that email as being invalid; yet, that email is the same email address that my
receipt was sent to.  So, how to proceed?

**Comment by vikaskookna** [comment]
Hi @johncblacker can you please mail us on ask.me@pyimagesearch.com for this issue

**Comment by johncblacker** [comment]
Sorry to take so long to get back to you.  I had to download the Raspbian.zip file several times before I got one where the MD5 checksum matched.

I’m on my way now, thank you.

 

John
