### ISSUE TITLE
Pre complied image is not supported on Raspberry PI4 4GB. 

### ISSUE THREAD

**Issue by abhiporanki** [PyImageSearch/Raspberry-Pi-for-Computer-Vision-RPi4CV#7]
_Please use this template while reporting bugs inside RPi4CV. Issues related to personal project questions or code that we haven't authored will automatically be closed._

## Are you using one of our development environments? 

We provide a preconfigured AWS AMI and a VM to help our customers skip the environment setup part and jump straight to development. We highly suggest using one of our development environments to run our code. 

If the issue is not related to code, then you can simply skip this question. 

## If you are using your own development environment then please provide the following details.

* GPU model and CUDA version: (skip if not application) 
* OS Platform: Pre compiled Image
* Python version: 
* OpenCV version: 
* TensorFlow version:

## Describe the issue 

Setting up of Raspberry PI4B from precompiled image. once image is flashed on to SD and during boot up, welcome screen mentioning software is compatible with the board. 

Please be clear and concise. Don't forget to include the Bundle and chapter names where you have found issues.

**Comment by vikaskookna** [comment]
Hi @abhiporanki, the pre-compiled image is supported for a 32 GB SD card and not below that, please check [this](https://pyimagesearch.com/2016/11/21/raspbian-opencv-pre-configured-and-pre-installed/?_ga=2.235223943.745544393.1649222137-1614231343.1634395940) out for more info.
![image](https://user-images.githubusercontent.com/17147416/161901652-3f357165-6e5c-42f2-b886-4630209050eb.png)

**Comment by abhiporanki** [comment]
I tried with 32 GB SD card as recommedned and it is still same issue. Unfortunately even the DIY steps provided to build from scratch does not seems to be valid anymore. Spent close to 2 days with all possible solutions (claims to be). Appreciate if support team closes the ticket after confirmation Closing the issue addressing is not expected.
