### ISSUE TITLE
Issue with pre compiled image and DIY steps

### ISSUE THREAD

**Issue by abhiporanki** [PyImageSearch/Raspberry-Pi-for-Computer-Vision-RPi4CV#8]
This is a follow up bug I am reporting after the previous reported bug was **closed without resolution.** 

1. Provided pre compiled image does not support Raspberry PI 4/8GB with recommended card of 32GB or any size.
2. DIY steps provided does not seems valid anymore. URL seems changed and steps provided to import numpy does not seems to be working.

Appreciate if appropriate steps are updated in blog anywhere before closing the issue marking resolved.

Regards,
Abhi

**Comment by vikaskookna** [comment]
@abhiporanki Can you please be more specific and tell me the error you're getting with screenshots attached

**Comment by abhiporanki** [comment]
@vikaskookna 

After referring to previously logged issues on same issue, I made sure to burn the image in 32GB SD on windows platform. Upon trying to boot " software not supported."
[Pi boot error.docx](https://github.com/PyImageSearch/Raspberry-Pi-for-Computer-Vision-RPi4CV/files/8481817/Pi.boot.error.docx)

DIY blog for building from scratch seems to have hit dead end too, NumPy wheel building stage failing.

PS: URL for WGET openvino needs a bit update, I had to manually update to get thru that step.

Appreciate your assistance on this.

Regards,
Abhiram.

**Comment by vikaskookna** [comment]
@abhiporanki  If your checksum is right and you're using ```Raspbian3B_4B.img.gz``` but still getting this error there's a problem with the Pi and you have to update, can you please update your Pi.

Install the latest Raspbian/Raspberry Pi OS on an SD Card
Make sure you are using Ethernet
Run the following commands
```sudo apt update && sudo apt full-upgrade -y```
```reboot```

Hope this is of some help.

**Comment by abhiporanki** [comment]
@vikaskookna  - I do not think this is very helpful, I make sure to have libraries to most latest and perform these to avoid any such as a best practice. Let me know if I can provide any specific information that can really solve the issue.

**Comment by vikaskookna** [comment]
@abhishekthanki Can you please have a look at this issue and update ASAP.

**Comment by abhishekthanki** [comment]
Hi @abhiporanki,

I have seen that error related to the image previously and the fix was to update the image to use newer version of Raspberry Pi OS. I will look into this but before I do that, can you tell me when did you buy your raspberry pi device?

**Comment by abhiporanki** [comment]
Hello @abhishekthanki  - I have multiple variants of Pi (Including 4GB, 8GB & CM4 versions) and most of them are recents buys. I initially suspected maybe (just a wild hunch). but was not entirely true. Let me know if I can provide any additional details

**Comment by vikaskookna** [comment]
@abhishekthanki can you please provide any ETA for this?

**Comment by vikaskookna** [comment]
@abhishekthanki @Jon1776 Please update me on this

**Comment by vikaskookna** [comment]
@abhishekthanki @Jon1776 Abhishek can you please update me on this?

**Comment by shumwaymark** [comment]
The current SD card image Raspbian3B_4B.img.gz (12-05-2019 )  will not boot on newer firmware.  So when purchasing a new Raspberry Pi, beware:

![RPi_boot_failure](https://user-images.githubusercontent.com/55546868/188036965-1a7ed17d-2b27-4360-93e3-8507438768fc.jpg)

I had an older RPi4B that was still able to boot off that image.  After running the apt-update/upgrade, that same SD card will now boot on the newer firmware. 

Still need a solution going forward.  It would be great to get an updated image for the newer hardware / software, but do not even know if that is in the works, will ever happen.

**Comment by vikaskookna** [comment]
@shumwaymark updated image from PyImageSearch has been released for 4B

**Comment by shumwaymark** [comment]
Thanks @vikaskookna. Where can we find the updated image? Not seeing this on the https://pyimagesearch.dpdcart.com portal.

**Comment by vikaskookna** [comment]
@shumwaymark when you purchase the book you will get along with that from Kajabi.

**Comment by shumwaymark** [comment]
Thanks @vikaskookna.  Purchased the book _a couple of years ago_.   Was hoping for an updated image, since the one I have won't boot on the newer boards.  Your comment when the issues was closed was that _a new image was released_,  However, when I checked the portal....  the date on the RPi image is 12/2020.   So, is THAT the new image??  With a date from 2 years ago?  Just trying to confirm, thanks again!

**Comment by vikaskookna** [comment]
@shumwaymark You need to log in here https://pyimagesearch.mykajabi.com/login and use the password I shared on your email. You will find the updated image in the downloads section
<img width="911" alt="image" src="https://user-images.githubusercontent.com/17147416/203810002-c2269ee7-d2aa-451c-900c-e72948c96abc.png">

**Comment by shumwaymark** [comment]
Thanks @vikaskookna - that link expired before I saw the email.  So there is a different domain name now?  ....mykajbi.com?  Guessing this site has moved, and existing customer accounts were not transferred?   Or did I miss the communication?  

Still hopeful, please let me know if this can be resolved.  Thanks again.

**Comment by vikaskookna** [comment]
@shumwaymark sent again
